// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/tokenlive/tokenlive-admin/internal/mods"
	"github.com/tokenlive/tokenlive-admin/internal/mods/dashboard"
	api5 "github.com/tokenlive/tokenlive-admin/internal/mods/dashboard/api"
	"github.com/tokenlive/tokenlive-admin/internal/mods/ops"
	api6 "github.com/tokenlive/tokenlive-admin/internal/mods/ops/api"
	biz2 "github.com/tokenlive/tokenlive-admin/internal/mods/ops/biz"
	dal2 "github.com/tokenlive/tokenlive-admin/internal/mods/ops/dal"
	"github.com/tokenlive/tokenlive-admin/internal/mods/policy"
	api4 "github.com/tokenlive/tokenlive-admin/internal/mods/policy/api"
	biz4 "github.com/tokenlive/tokenlive-admin/internal/mods/policy/biz"
	dal4 "github.com/tokenlive/tokenlive-admin/internal/mods/policy/dal"
	"github.com/tokenlive/tokenlive-admin/internal/mods/rbac"
	"github.com/tokenlive/tokenlive-admin/internal/mods/rbac/api"
	"github.com/tokenlive/tokenlive-admin/internal/mods/rbac/biz"
	"github.com/tokenlive/tokenlive-admin/internal/mods/rbac/dal"
	"github.com/tokenlive/tokenlive-admin/internal/mods/resource"
	api2 "github.com/tokenlive/tokenlive-admin/internal/mods/resource/api"
	biz3 "github.com/tokenlive/tokenlive-admin/internal/mods/resource/biz"
	dal3 "github.com/tokenlive/tokenlive-admin/internal/mods/resource/dal"
	"github.com/tokenlive/tokenlive-admin/internal/mods/space"
	api3 "github.com/tokenlive/tokenlive-admin/internal/mods/space/api"
	biz5 "github.com/tokenlive/tokenlive-admin/internal/mods/space/biz"
	dal5 "github.com/tokenlive/tokenlive-admin/internal/mods/space/dal"
	"github.com/tokenlive/tokenlive-admin/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCacher(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup3, err := InitAuth(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	trans := &util.Trans{
		DB: db,
	}
	menu := &dal.Menu{
		DB: db,
	}
	menuResource := &dal.MenuResource{
		DB: db,
	}
	roleMenu := &dal.RoleMenu{
		DB: db,
	}
	bizMenu := &biz.Menu{
		Cache:           cacher,
		Trans:           trans,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleMenuDAL:     roleMenu,
	}
	apiMenu := &api.Menu{
		MenuBIZ: bizMenu,
	}
	role := &dal.Role{
		DB: db,
	}
	userRole := &dal.UserRole{
		DB: db,
	}
	auditLog := &dal2.AuditLog{
		DB: db,
	}
	bizAuditLog := &biz2.AuditLog{
		Trans:       trans,
		AuditLogDAL: auditLog,
	}
	bizRole := &biz.Role{
		Cache:       cacher,
		Trans:       trans,
		RoleDAL:     role,
		RoleMenuDAL: roleMenu,
		UserRoleDAL: userRole,
		AuditLogBIZ: bizAuditLog,
	}
	apiRole := &api.Role{
		RoleBIZ: bizRole,
	}
	user := &dal.User{
		DB: db,
	}
	bizUser := &biz.User{
		Cache:       cacher,
		Trans:       trans,
		UserDAL:     user,
		UserRoleDAL: userRole,
		AuditLogBIZ: bizAuditLog,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	login := &biz.Login{
		Cache:       cacher,
		Auth:        auther,
		UserDAL:     user,
		UserRoleDAL: userRole,
		MenuDAL:     menu,
		UserBIZ:     bizUser,
		AuditLogBIZ: bizAuditLog,
	}
	apiLogin := &api.Login{
		LoginBIZ: login,
	}
	externalIdentity := &dal.ExternalIdentity{
		DB: db,
	}
	tenant := &dal.Tenant{
		DB: db,
	}
	tenantModel := &dal.TenantModel{
		DB: db,
	}
	client := InitHTTPClient()
	oAuth := &biz.OAuth{
		Cache:               cacher,
		Trans:               trans,
		ExternalIdentityDAL: externalIdentity,
		UserDAL:             user,
		UserRoleDAL:         userRole,
		TenantDAL:           tenant,
		TenantModelDAL:      tenantModel,
		RoleDAL:             role,
		LoginBIZ:            login,
		HTTPClient:          client,
	}
	apiOAuth := &api.OAuth{
		OAuthBIZ: oAuth,
	}
	logger := &dal.Logger{
		DB: db,
	}
	bizLogger := &biz.Logger{
		LoggerDAL: logger,
	}
	apiLogger := &api.Logger{
		LoggerBIZ: bizLogger,
	}
	userAPIKey := &dal.UserAPIKey{
		DB: db,
	}
	redisClient := biz.ProvideRedisClient()
	bizUserAPIKey := &biz.UserAPIKey{
		Trans:         trans,
		UserAPIKeyDAL: userAPIKey,
		UserDAL:       user,
		RedisClient:   redisClient,
		AuditLogBIZ:   bizAuditLog,
	}
	apiUserAPIKey := &api.UserAPIKey{
		UserAPIKeyBIZ: bizUserAPIKey,
	}
	bizTenant := &biz.Tenant{
		Trans:       trans,
		TenantDAL:   tenant,
		UserDAL:     user,
		RedisClient: redisClient,
		AuditLogBIZ: bizAuditLog,
	}
	apiTenant := &api.Tenant{
		TenantBIZ: bizTenant,
	}
	bizTenantModel := &biz.TenantModel{
		Trans:          trans,
		TenantModelDAL: tenantModel,
		RedisClient:    redisClient,
		AuditLogBIZ:    bizAuditLog,
	}
	apiTenantModel := &api.TenantModel{
		TenantModelBIZ: bizTenantModel,
	}
	tenantEndpoint := &dal.TenantEndpoint{
		DB: db,
	}
	bizTenantEndpoint := &biz.TenantEndpoint{
		Trans:             trans,
		TenantEndpointDAL: tenantEndpoint,
		RedisClient:       redisClient,
		AuditLogBIZ:       bizAuditLog,
	}
	apiTenantEndpoint := &api.TenantEndpoint{
		TenantEndpointBIZ: bizTenantEndpoint,
	}
	casbinx := &rbac.Casbinx{
		DB:              db,
		Cache:           cacher,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleDAL:         role,
	}
	rbacRBAC := &rbac.RBAC{
		DB:                db,
		MenuAPI:           apiMenu,
		RoleAPI:           apiRole,
		UserAPI:           apiUser,
		LoginAPI:          apiLogin,
		OAuthAPI:          apiOAuth,
		LoggerAPI:         apiLogger,
		UserAPIKeyAPI:     apiUserAPIKey,
		TenantAPI:         apiTenant,
		TenantModelAPI:    apiTenantModel,
		TenantEndpointAPI: apiTenantEndpoint,
		Casbinx:           casbinx,
	}
	endpoint := &dal3.Endpoint{
		DB: db,
	}
	model := &dal3.Model{
		DB: db,
	}
	modelAlias := &dal3.ModelAlias{
		DB: db,
	}
	configRedisSync := &biz3.ConfigRedisSync{
		RedisClient:   redisClient,
		EndpointDAL:   endpoint,
		ModelDAL:      model,
		ModelAliasDAL: modelAlias,
	}
	provider := &dal3.Provider{
		DB: db,
	}
	dataPermission := &dal3.DataPermission{
		DB: db,
	}
	bizDataPermission := &biz3.DataPermission{
		Trans:             trans,
		DataPermissionDAL: dataPermission,
	}
	bizProvider := &biz3.Provider{
		Trans:             trans,
		Cache:             cacher,
		ProviderDAL:       provider,
		DataPermissionBIZ: bizDataPermission,
		ConfigRedisSync:   configRedisSync,
		AuditLogBIZ:       bizAuditLog,
	}
	apiProvider := &api2.Provider{
		ProviderBIZ: bizProvider,
	}
	bizEndpoint := &biz3.Endpoint{
		Trans:             trans,
		EndpointDAL:       endpoint,
		DataPermissionBIZ: bizDataPermission,
		ModelDAL:          model,
		ProviderDAL:       provider,
		ConfigRedisSync:   configRedisSync,
		RedisClient:       redisClient,
		AuditLogBIZ:       bizAuditLog,
	}
	apiEndpoint := &api2.Endpoint{
		EndpointBIZ: bizEndpoint,
	}
	policyLoadbalance := &dal4.PolicyLoadbalance{
		DB: db,
	}
	policyRoute := &dal4.PolicyRoute{
		DB: db,
	}
	policyLimit := &dal4.PolicyLimit{
		DB: db,
	}
	policyCircuitBreak := &dal4.PolicyCircuitBreak{
		DB: db,
	}
	policyInvocation := &dal4.PolicyInvocation{
		DB: db,
	}
	policyTagging := &dal4.PolicyTagging{
		DB: db,
	}
	policyRedisSync := &biz4.PolicyRedisSync{
		RedisClient:           redisClient,
		PolicyLoadbalanceDAL:  policyLoadbalance,
		PolicyRouteDAL:        policyRoute,
		PolicyLimitDAL:        policyLimit,
		PolicyCircuitBreakDAL: policyCircuitBreak,
		PolicyInvocationDAL:   policyInvocation,
		PolicyTaggingDAL:      policyTagging,
		ModelDAL:              model,
	}
	bizModel := &biz3.Model{
		Trans:             trans,
		ModelDAL:          model,
		DataPermissionBIZ: bizDataPermission,
		ConfigRedisSync:   configRedisSync,
		PolicyRedisSync:   policyRedisSync,
		RedisClient:       redisClient,
		AuditLogBIZ:       bizAuditLog,
	}
	apiModel := &api2.Model{
		ModelBIZ: bizModel,
	}
	bizModelAlias := &biz3.ModelAlias{
		Trans:           trans,
		ModelAliasDAL:   modelAlias,
		ModelDAL:        model,
		ConfigRedisSync: configRedisSync,
	}
	apiModelAlias := &api2.ModelAlias{
		ModelAliasBIZ: bizModelAlias,
	}
	apiDataPermission := &api2.DataPermission{
		DataPermissionBIZ: bizDataPermission,
	}
	modelCatalog := &dal3.ModelCatalog{
		DB: db,
	}
	modelCatalogI18n := &dal3.ModelCatalogI18n{
		DB: db,
	}
	bizModelCatalog := &biz3.ModelCatalog{
		Trans:               trans,
		ModelCatalogDAL:     modelCatalog,
		ModelCatalogI18nDAL: modelCatalogI18n,
		AuditLogBIZ:         bizAuditLog,
	}
	apiModelCatalog := &api2.ModelCatalog{
		ModelCatalogBIZ: bizModelCatalog,
	}
	bizModelCatalogI18n := &biz3.ModelCatalogI18n{
		Trans:               trans,
		ModelCatalogI18nDAL: modelCatalogI18n,
		ModelCatalogDAL:     modelCatalog,
	}
	apiModelCatalogI18n := &api2.ModelCatalogI18n{
		ModelCatalogI18nBIZ: bizModelCatalogI18n,
	}
	modelPriceVersion := &dal3.ModelPriceVersion{
		DB: db,
	}
	bizModelPriceVersion := &biz3.ModelPriceVersion{
		Trans:                trans,
		ModelPriceVersionDAL: modelPriceVersion,
		ModelCatalogDAL:      modelCatalog,
		AuditLogBIZ:          bizAuditLog,
	}
	apiModelPriceVersion := &api2.ModelPriceVersion{
		ModelPriceVersionBIZ: bizModelPriceVersion,
	}
	gatewaySync := &biz3.GatewaySync{
		DB:            db,
		EndpointDAL:   endpoint,
		ModelDAL:      model,
		ModelAliasDAL: modelAlias,
	}
	eventLog := &dal2.EventLog{
		DB: db,
	}
	eventBiz := &biz2.EventBiz{
		EventDAL: eventLog,
	}
	apiGatewaySync := &api2.GatewaySync{
		GatewaySyncBIZ: gatewaySync,
		EventBiz:       eventBiz,
	}
	resourceResource := &resource.Resource{
		DB:                   db,
		ConfigRedisSync:      configRedisSync,
		ProviderAPI:          apiProvider,
		EndpointAPI:          apiEndpoint,
		ModelAPI:             apiModel,
		ModelAliasAPI:        apiModelAlias,
		DataPermissionAPI:    apiDataPermission,
		ModelCatalogAPI:      apiModelCatalog,
		ModelCatalogI18nAPI:  apiModelCatalogI18n,
		ModelPriceVersionAPI: apiModelPriceVersion,
		GatewaySyncAPI:       apiGatewaySync,
	}
	dalSpace := &dal5.Space{
		DB: db,
	}
	bizSpace := &biz5.Space{
		Trans:    trans,
		SpaceDAL: dalSpace,
	}
	apiSpace := &api3.Space{
		SpaceBIZ: bizSpace,
	}
	spaceSpace := &space.Space{
		DB:       db,
		SpaceAPI: apiSpace,
	}
	bizPolicyLoadbalance := &biz4.PolicyLoadbalance{
		Trans:                trans,
		PolicyLoadbalanceDAL: policyLoadbalance,
		PolicyRedisSync:      policyRedisSync,
		ModelDAL:             model,
		DataPermissionDAL:    dataPermission,
		AuditLogBIZ:          bizAuditLog,
	}
	apiPolicyLoadbalance := &api4.PolicyLoadbalance{
		PolicyLoadbalanceBIZ: bizPolicyLoadbalance,
	}
	bizPolicyRoute := &biz4.PolicyRoute{
		Trans:             trans,
		PolicyRouteDAL:    policyRoute,
		PolicyRedisSync:   policyRedisSync,
		ModelDAL:          model,
		DataPermissionDAL: dataPermission,
		AuditLogBIZ:       bizAuditLog,
	}
	apiPolicyRoute := &api4.PolicyRoute{
		PolicyRouteBIZ: bizPolicyRoute,
	}
	policyRouteDetail := &dal4.PolicyRouteDetail{
		DB: db,
	}
	bizPolicyRouteDetail := &biz4.PolicyRouteDetail{
		Trans:                trans,
		PolicyRouteDetailDAL: policyRouteDetail,
		PolicyRouteDAL:       policyRoute,
		PolicyRedisSync:      policyRedisSync,
	}
	apiPolicyRouteDetail := &api4.PolicyRouteDetail{
		PolicyRouteDetailBIZ: bizPolicyRouteDetail,
	}
	bizPolicyLimit := &biz4.PolicyLimit{
		Trans:             trans,
		PolicyLimitDAL:    policyLimit,
		PolicyRedisSync:   policyRedisSync,
		ModelDAL:          model,
		DataPermissionDAL: dataPermission,
		AuditLogBIZ:       bizAuditLog,
	}
	apiPolicyLimit := &api4.PolicyLimit{
		PolicyLimitBIZ: bizPolicyLimit,
	}
	bizPolicyCircuitBreak := &biz4.PolicyCircuitBreak{
		Trans:                 trans,
		PolicyCircuitBreakDAL: policyCircuitBreak,
		PolicyRedisSync:       policyRedisSync,
		ModelDAL:              model,
		DataPermissionDAL:     dataPermission,
		AuditLogBIZ:           bizAuditLog,
	}
	apiPolicyCircuitBreak := &api4.PolicyCircuitBreak{
		PolicyCircuitBreakBIZ: bizPolicyCircuitBreak,
	}
	bizPolicyInvocation := &biz4.PolicyInvocation{
		Trans:               trans,
		PolicyInvocationDAL: policyInvocation,
		PolicyRedisSync:     policyRedisSync,
		ModelDAL:            model,
		DataPermissionDAL:   dataPermission,
		AuditLogBIZ:         bizAuditLog,
	}
	apiPolicyInvocation := &api4.PolicyInvocation{
		PolicyInvocationBIZ: bizPolicyInvocation,
	}
	bizPolicyTagging := &biz4.PolicyTagging{
		Trans:             trans,
		PolicyTaggingDAL:  policyTagging,
		PolicyRedisSync:   policyRedisSync,
		ModelDAL:          model,
		DataPermissionDAL: dataPermission,
		AuditLogBIZ:       bizAuditLog,
	}
	apiPolicyTagging := &api4.PolicyTagging{
		PolicyTaggingBIZ: bizPolicyTagging,
	}
	policyPolicy := &policy.Policy{
		DB:                    db,
		PolicyLoadbalanceAPI:  apiPolicyLoadbalance,
		PolicyRouteAPI:        apiPolicyRoute,
		PolicyRouteDetailAPI:  apiPolicyRouteDetail,
		PolicyLimitAPI:        apiPolicyLimit,
		PolicyCircuitBreakAPI: apiPolicyCircuitBreak,
		PolicyInvocationAPI:   apiPolicyInvocation,
		PolicyTaggingAPI:      apiPolicyTagging,
	}
	apiDashboard := &api5.Dashboard{
		DB:          db,
		RedisClient: redisClient,
		RedisSync:   configRedisSync,
	}
	dashboardDashboard := &dashboard.Dashboard{
		DashboardAPI: apiDashboard,
	}
	wsHub := api6.NewWSHub()
	eventAPI := &api6.EventAPI{
		EventBIZ: eventBiz,
		Hub:      wsHub,
	}
	apiAuditLog := &api6.AuditLog{
		AuditLogBIZ: bizAuditLog,
	}
	portalUser := &biz2.PortalUser{}
	portalUserAPI := &api6.PortalUserAPI{
		PortalUserBIZ: portalUser,
	}
	eventSubscriber := ops.ProvideEventSubscriber(redisClient)
	consumer := &biz2.Consumer{
		Subscriber: eventSubscriber,
		EventDAL:   eventLog,
	}
	cleanupTask := &biz2.CleanupTask{
		DB: db,
	}
	opsOps := &ops.Ops{
		DB:            db,
		EventAPI:      eventAPI,
		AuditLogAPI:   apiAuditLog,
		PortalUserAPI: portalUserAPI,
		Consumer:      consumer,
		CleanupTask:   cleanupTask,
		Hub:           wsHub,
	}
	modsMods := &mods.Mods{
		RBAC:      rbacRBAC,
		Resource:  resourceResource,
		Space:     spaceSpace,
		Policy:    policyPolicy,
		Dashboard: dashboardDashboard,
		Ops:       opsOps,
	}
	injector := &Injector{
		DB:    db,
		Cache: cacher,
		Auth:  auther,
		M:     modsMods,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
