// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/tokenlive/tokenlive-admin/internal/mods"
	"github.com/tokenlive/tokenlive-admin/internal/mods/dashboard"
	api5 "github.com/tokenlive/tokenlive-admin/internal/mods/dashboard/api"
	"github.com/tokenlive/tokenlive-admin/internal/mods/policy"
	api4 "github.com/tokenlive/tokenlive-admin/internal/mods/policy/api"
	biz3 "github.com/tokenlive/tokenlive-admin/internal/mods/policy/biz"
	dal3 "github.com/tokenlive/tokenlive-admin/internal/mods/policy/dal"
	"github.com/tokenlive/tokenlive-admin/internal/mods/rbac"
	"github.com/tokenlive/tokenlive-admin/internal/mods/rbac/api"
	"github.com/tokenlive/tokenlive-admin/internal/mods/rbac/biz"
	"github.com/tokenlive/tokenlive-admin/internal/mods/rbac/dal"
	"github.com/tokenlive/tokenlive-admin/internal/mods/resource"
	api2 "github.com/tokenlive/tokenlive-admin/internal/mods/resource/api"
	biz2 "github.com/tokenlive/tokenlive-admin/internal/mods/resource/biz"
	dal2 "github.com/tokenlive/tokenlive-admin/internal/mods/resource/dal"
	"github.com/tokenlive/tokenlive-admin/internal/mods/space"
	api3 "github.com/tokenlive/tokenlive-admin/internal/mods/space/api"
	biz4 "github.com/tokenlive/tokenlive-admin/internal/mods/space/biz"
	dal4 "github.com/tokenlive/tokenlive-admin/internal/mods/space/dal"
	"github.com/tokenlive/tokenlive-admin/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCacher(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup3, err := InitAuth(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	trans := &util.Trans{
		DB: db,
	}
	menu := &dal.Menu{
		DB: db,
	}
	menuResource := &dal.MenuResource{
		DB: db,
	}
	roleMenu := &dal.RoleMenu{
		DB: db,
	}
	bizMenu := &biz.Menu{
		Cache:           cacher,
		Trans:           trans,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleMenuDAL:     roleMenu,
	}
	apiMenu := &api.Menu{
		MenuBIZ: bizMenu,
	}
	role := &dal.Role{
		DB: db,
	}
	userRole := &dal.UserRole{
		DB: db,
	}
	bizRole := &biz.Role{
		Cache:       cacher,
		Trans:       trans,
		RoleDAL:     role,
		RoleMenuDAL: roleMenu,
		UserRoleDAL: userRole,
	}
	apiRole := &api.Role{
		RoleBIZ: bizRole,
	}
	user := &dal.User{
		DB: db,
	}
	bizUser := &biz.User{
		Cache:       cacher,
		Trans:       trans,
		UserDAL:     user,
		UserRoleDAL: userRole,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	login := &biz.Login{
		Cache:       cacher,
		Auth:        auther,
		UserDAL:     user,
		UserRoleDAL: userRole,
		MenuDAL:     menu,
		UserBIZ:     bizUser,
	}
	apiLogin := &api.Login{
		LoginBIZ: login,
	}
	logger := &dal.Logger{
		DB: db,
	}
	bizLogger := &biz.Logger{
		LoggerDAL: logger,
	}
	apiLogger := &api.Logger{
		LoggerBIZ: bizLogger,
	}
	userAPIKey := &dal.UserAPIKey{
		DB: db,
	}
	client := biz.ProvideRedisClient()
	bizUserAPIKey := &biz.UserAPIKey{
		Trans:         trans,
		UserAPIKeyDAL: userAPIKey,
		UserDAL:       user,
		RedisClient:   client,
	}
	apiUserAPIKey := &api.UserAPIKey{
		UserAPIKeyBIZ: bizUserAPIKey,
	}
	tenant := &dal.Tenant{
		DB: db,
	}
	bizTenant := &biz.Tenant{
		Trans:       trans,
		TenantDAL:   tenant,
		UserDAL:     user,
		RedisClient: client,
	}
	apiTenant := &api.Tenant{
		TenantBIZ: bizTenant,
	}
	tenantModel := &dal.TenantModel{
		DB: db,
	}
	bizTenantModel := &biz.TenantModel{
		Trans:          trans,
		TenantModelDAL: tenantModel,
		RedisClient:    client,
	}
	apiTenantModel := &api.TenantModel{
		TenantModelBIZ: bizTenantModel,
	}
	tenantModelProvider := &dal.TenantModelProvider{
		DB: db,
	}
	bizTenantModelProvider := &biz.TenantModelProvider{
		Trans:                  trans,
		TenantModelProviderDAL: tenantModelProvider,
		RedisClient:            client,
	}
	apiTenantModelProvider := &api.TenantModelProvider{
		TenantModelProviderBIZ: bizTenantModelProvider,
	}
	tenantEndpoint := &dal.TenantEndpoint{
		DB: db,
	}
	bizTenantEndpoint := &biz.TenantEndpoint{
		Trans:             trans,
		TenantEndpointDAL: tenantEndpoint,
		RedisClient:       client,
	}
	apiTenantEndpoint := &api.TenantEndpoint{
		TenantEndpointBIZ: bizTenantEndpoint,
	}
	casbinx := &rbac.Casbinx{
		DB:              db,
		Cache:           cacher,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleDAL:         role,
	}
	rbacRBAC := &rbac.RBAC{
		DB:                     db,
		MenuAPI:                apiMenu,
		RoleAPI:                apiRole,
		UserAPI:                apiUser,
		LoginAPI:               apiLogin,
		LoggerAPI:              apiLogger,
		UserAPIKeyAPI:          apiUserAPIKey,
		TenantAPI:              apiTenant,
		TenantModelAPI:         apiTenantModel,
		TenantModelProviderAPI: apiTenantModelProvider,
		TenantEndpointAPI:      apiTenantEndpoint,
		Casbinx:                casbinx,
	}
	provider := &dal2.Provider{
		DB: db,
	}
	dataPermission := &dal2.DataPermission{
		DB: db,
	}
	bizDataPermission := &biz2.DataPermission{
		Trans:             trans,
		DataPermissionDAL: dataPermission,
	}
	endpoint := &dal2.Endpoint{
		DB: db,
	}
	model := &dal2.Model{
		DB: db,
	}
	modelAlias := &dal2.ModelAlias{
		DB: db,
	}
	configRedisSync := &biz2.ConfigRedisSync{
		RedisClient:   client,
		EndpointDAL:   endpoint,
		ModelDAL:      model,
		ModelAliasDAL: modelAlias,
	}
	bizProvider := &biz2.Provider{
		Trans:             trans,
		ProviderDAL:       provider,
		DataPermissionBIZ: bizDataPermission,
		ConfigRedisSync:   configRedisSync,
	}
	apiProvider := &api2.Provider{
		ProviderBIZ: bizProvider,
	}
	bizEndpoint := &biz2.Endpoint{
		Trans:             trans,
		EndpointDAL:       endpoint,
		DataPermissionBIZ: bizDataPermission,
		ModelDAL:          model,
		ProviderDAL:       provider,
		ConfigRedisSync:   configRedisSync,
		RedisClient:       client,
	}
	apiEndpoint := &api2.Endpoint{
		EndpointBIZ: bizEndpoint,
	}
	policyBinding := &dal3.PolicyBinding{
		DB: db,
	}
	policyLoadbalance := &dal3.PolicyLoadbalance{
		DB: db,
	}
	policyRoute := &dal3.PolicyRoute{
		DB: db,
	}
	policyLimit := &dal3.PolicyLimit{
		DB: db,
	}
	policyCircuitBreak := &dal3.PolicyCircuitBreak{
		DB: db,
	}
	policyInvocation := &dal3.PolicyInvocation{
		DB: db,
	}
	policyTagging := &dal3.PolicyTagging{
		DB: db,
	}
	policyRedisSync := &biz3.PolicyRedisSync{
		RedisClient:           client,
		PolicyBindingDAL:      policyBinding,
		PolicyLoadbalanceDAL:  policyLoadbalance,
		PolicyRouteDAL:        policyRoute,
		PolicyLimitDAL:        policyLimit,
		PolicyCircuitBreakDAL: policyCircuitBreak,
		PolicyInvocationDAL:   policyInvocation,
		PolicyTaggingDAL:      policyTagging,
	}
	bizModel := &biz2.Model{
		Trans:             trans,
		ModelDAL:          model,
		DataPermissionBIZ: bizDataPermission,
		ConfigRedisSync:   configRedisSync,
		PolicyRedisSync:   policyRedisSync,
		RedisClient:       client,
	}
	apiModel := &api2.Model{
		ModelBIZ: bizModel,
	}
	bizModelAlias := &biz2.ModelAlias{
		Trans:           trans,
		ModelAliasDAL:   modelAlias,
		ModelDAL:        model,
		ConfigRedisSync: configRedisSync,
	}
	apiModelAlias := &api2.ModelAlias{
		ModelAliasBIZ: bizModelAlias,
	}
	apiDataPermission := &api2.DataPermission{
		DataPermissionBIZ: bizDataPermission,
	}
	resourceResource := &resource.Resource{
		DB:                db,
		ProviderAPI:       apiProvider,
		EndpointAPI:       apiEndpoint,
		ModelAPI:          apiModel,
		ModelAliasAPI:     apiModelAlias,
		DataPermissionAPI: apiDataPermission,
	}
	dalSpace := &dal4.Space{
		DB: db,
	}
	bizSpace := &biz4.Space{
		Trans:    trans,
		SpaceDAL: dalSpace,
	}
	apiSpace := &api3.Space{
		SpaceBIZ: bizSpace,
	}
	spaceSpace := &space.Space{
		DB:       db,
		SpaceAPI: apiSpace,
	}
	bizPolicyLoadbalance := &biz3.PolicyLoadbalance{
		Trans:                trans,
		PolicyLoadbalanceDAL: policyLoadbalance,
		PolicyBindingDAL:     policyBinding,
		PolicyRedisSync:      policyRedisSync,
	}
	apiPolicyLoadbalance := &api4.PolicyLoadbalance{
		PolicyLoadbalanceBIZ: bizPolicyLoadbalance,
	}
	bizPolicyRoute := &biz3.PolicyRoute{
		Trans:            trans,
		PolicyRouteDAL:   policyRoute,
		PolicyBindingDAL: policyBinding,
		PolicyRedisSync:  policyRedisSync,
	}
	apiPolicyRoute := &api4.PolicyRoute{
		PolicyRouteBIZ: bizPolicyRoute,
	}
	policyRouteDetail := &dal3.PolicyRouteDetail{
		DB: db,
	}
	bizPolicyRouteDetail := &biz3.PolicyRouteDetail{
		Trans:                trans,
		PolicyRouteDetailDAL: policyRouteDetail,
	}
	apiPolicyRouteDetail := &api4.PolicyRouteDetail{
		PolicyRouteDetailBIZ: bizPolicyRouteDetail,
	}
	bizPolicyLimit := &biz3.PolicyLimit{
		Trans:            trans,
		PolicyLimitDAL:   policyLimit,
		PolicyBindingDAL: policyBinding,
		PolicyRedisSync:  policyRedisSync,
	}
	apiPolicyLimit := &api4.PolicyLimit{
		PolicyLimitBIZ: bizPolicyLimit,
	}
	bizPolicyCircuitBreak := &biz3.PolicyCircuitBreak{
		Trans:                 trans,
		PolicyCircuitBreakDAL: policyCircuitBreak,
		PolicyBindingDAL:      policyBinding,
		PolicyRedisSync:       policyRedisSync,
	}
	apiPolicyCircuitBreak := &api4.PolicyCircuitBreak{
		PolicyCircuitBreakBIZ: bizPolicyCircuitBreak,
	}
	bizPolicyInvocation := &biz3.PolicyInvocation{
		Trans:               trans,
		PolicyInvocationDAL: policyInvocation,
		PolicyBindingDAL:    policyBinding,
		PolicyRedisSync:     policyRedisSync,
	}
	apiPolicyInvocation := &api4.PolicyInvocation{
		PolicyInvocationBIZ: bizPolicyInvocation,
	}
	bizPolicyBinding := &biz3.PolicyBinding{
		Trans:            trans,
		PolicyBindingDAL: policyBinding,
		PolicyRedisSync:  policyRedisSync,
	}
	apiPolicyBinding := &api4.PolicyBinding{
		PolicyBindingBIZ: bizPolicyBinding,
	}
	bizPolicyTagging := &biz3.PolicyTagging{
		Trans:            trans,
		PolicyTaggingDAL: policyTagging,
		PolicyBindingDAL: policyBinding,
		PolicyRedisSync:  policyRedisSync,
	}
	apiPolicyTagging := &api4.PolicyTagging{
		PolicyTaggingBIZ: bizPolicyTagging,
	}
	policyPolicy := &policy.Policy{
		DB:                    db,
		PolicyLoadbalanceAPI:  apiPolicyLoadbalance,
		PolicyRouteAPI:        apiPolicyRoute,
		PolicyRouteDetailAPI:  apiPolicyRouteDetail,
		PolicyLimitAPI:        apiPolicyLimit,
		PolicyCircuitBreakAPI: apiPolicyCircuitBreak,
		PolicyInvocationAPI:   apiPolicyInvocation,
		PolicyBindingAPI:      apiPolicyBinding,
		PolicyTaggingAPI:      apiPolicyTagging,
	}
	apiDashboard := &api5.Dashboard{
		DB:          db,
		RedisClient: client,
		RedisSync:   configRedisSync,
	}
	dashboardDashboard := &dashboard.Dashboard{
		DashboardAPI: apiDashboard,
	}
	modsMods := &mods.Mods{
		RBAC:      rbacRBAC,
		Resource:  resourceResource,
		Space:     spaceSpace,
		Policy:    policyPolicy,
		Dashboard: dashboardDashboard,
	}
	injector := &Injector{
		DB:    db,
		Cache: cacher,
		Auth:  auther,
		M:     modsMods,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
